# .github/workflows/scheduled-builds.yml
name: Trigger Pause Session

on:
  schedule:
    # Runs "at 10pm" (see https://crontab.guru)
    Please remove the # to activate the cron
    #- cron: '25 8 * * *'
jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}
      - run: |
          grid session pause ${{ secrets.SESSION_NAME }} 
          
           
            
